name: RedCandleCoffee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c0000'
    - '#4d4f56'
    - '#8ba6c0'
    - '#6d7e8c'
    - '#cfd7da'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
