name: RedCandleCoffee
favicon: null
layout_spectrum: 0
typography_spectrum: 0.88992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#270000'
    - '#3c3945'
    - '#55586a'
    - '#7a85a0'
    - '#929fb8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
