name: RedCandleCoffee
favicon: null
layout_spectrum: 0.5995249117258936
typography_spectrum: 0.17228077771142125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0884652272798121
  lightness: 0.3899224656634033
  saturation: 0.8105760223697871
  rhythmicContrast: 0.510586540447548
purpose: []
